// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://iwqievvbebcctqwamuat.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3cWlldnZiZWJjY3Rxd2FtdWF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAxNDY4NzAsImV4cCI6MjA0NTcyMjg3MH0.k9zH27JV4wkeXoFew4o1nJMXGKLXyXVE9YiJ-n4x-Q4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);